Fix insert select planner crash
The following query was crashing the backend:

```
INSERT INTO field_indirection_test_1 (
  int_col, ct1_col.int_1,ct1_col.int_2
) SELECT 0, 1, 2;
-- crash
```

En passant, added more tests with sublink in distributed_types and found another
query with wrong behavior:

```
INSERT INTO domain_indirection_test (f1,f3.if1) SELECT 0, 1;
ERROR:  could not find a conversion path from type 23 to 17619
-- not the expected ERROR
```

Fixed them by using strip_implicit_coercions() on target entry expression
before checking for the presence of a subscript or fieldstore, else we
fail to find the existing ones and wrongly accept to execute unsafe
query.

Also:
pdate regress test to work with older PostgreSQL

In recent test added, `VALUES()` was used without alias as it is more flexible today.
Added an alias where required.

End:
Add test related to issue #4704

It is ok now, but I didn't bissect to known when it was fixed precisely.