Disallow colocating tables when collations don't match
- No need to make any changes for the following UDFs:

  - update_distributed_table_colocation()/create_distributed_table_concurrently()

    These are already checking whether collations of distribution keys match.

  - ALTER TABLE .. ALTER COLUMN .. TYPE .. COLLATE ..

    We already don't allow changing the collation of a distribution column.

- The following UDFs are fixed with this commit:

  These UDFs were not explicitly checking whether collation of the distribution
  keys of two distributed tables match, however, we were catching this via
  EnsurePartitionMetadataIsSane() when syncing metadata. And this incorrectly
  caused allowing to colocate two such distributed tables in a single-node setup
  as we don't have any nodes to sync metadata there. In such cases, we would only
  become aware of the situation **when adding a new node to the cluster etc.**.

  Otherwise, i.e., if we already had more than one nodes in the cluster, we were
  seeing this error while Citus is syncing metadata for the new / altered distributed
  table, which wasn't too bad but not ideal too:
  ```sql
  ERROR:  cannot colocate tables test_a_tbl_2 and test_a_tbl_1
  DETAIL:  Distribution column collations don't match for test_a_tbl_2 and test_a_tbl_1.
  CONTEXT:  while executing command on localhost:9701
  ```

  - create_distributed_table()

    To fix that, now EnsureTableCanBeColocatedWith() calls EnsureColumnTypeEquality()
    to perform necessary checks, which already ensures collation match.

    And to do that, now EnsureTableCanBeColocatedWith() has to accept distributionColumn
    Var as an argument (to be passed into EnsureColumnTypeEquality()), so now it doesn't
    have to accept distributionColumnType separately, so refactor accordingly.

    And to provide distributionColumn Var to EnsureTableCanBeColocatedWith(), similarly
    the call sites of the function also need to have distributionColumn Var, like
    FindColocateWithColocationId(). And now that FindColocateWithColocationId() accepts
    distributionColumn Var, it doesn't have to accept distributionColumnType and
    distributionColumnCollation separately, so refactor accordingly.

    Plus, now this UDF also correctly records the colocation groups with the correct
    distribution column collations.

  - alter_distributed_table()

    Make sure to check column collations.

- Also, now citus_finish_citus_upgrade() automatically fixes such colocation groups when
  executed after upgrading to Citus 14.

  This also helps removing the last alternative test output for
  upgrade_citus_finish_citus_upgrade. This is because, the recent change made in
  citus_finish_citus_upgrade() to automatically fix such colocation groups results in
  updating last_upgrade_version in pg_dist_node_metadata when upgrading to Citus 14,
  so the notice message in the mentioned test is now gone, so we don't anymore need to
  have an alternative output for that test.