Don't run tests in parallel to avoid relation open error
In PG15, columnar_first_row_number fails like follows
ERROR:  could not open relation with OID xxxxx

where that relation is created in columnar_query and dropped
simultaneously with our test.
Hence let's not run these tests in parallel.